[2021-03-12 11:23:20,351] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: conversion_flow.taskPrepare 2021-03-12T11:23:18+00:00 [queued]>
[2021-03-12 11:23:20,359] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: conversion_flow.taskPrepare 2021-03-12T11:23:18+00:00 [queued]>
[2021-03-12 11:23:20,359] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2021-03-12 11:23:20,359] {taskinstance.py:1043} INFO - Starting attempt 1 of 1
[2021-03-12 11:23:20,359] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2021-03-12 11:23:20,364] {taskinstance.py:1063} INFO - Executing <Task(PythonOperator): taskPrepare> on 2021-03-12T11:23:18+00:00
[2021-03-12 11:23:20,365] {standard_task_runner.py:52} INFO - Started process 2847 to run task
[2021-03-12 11:23:20,368] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'conversion_flow', 'taskPrepare', '2021-03-12T11:23:18+00:00', '--job-id', '13', '--pool', 'default_pool', '--raw', '--subdir', '/srv/app/src/ckanext-mysql2mongodb/ckanext/mysql2mongodb/data_conv/dag/conversion_flow.py', '--cfg-path', '/tmp/tmpjf17s8x3', '--error-file', '/tmp/tmp_1idz1i2']
[2021-03-12 11:23:20,369] {standard_task_runner.py:77} INFO - Job 13: Subtask taskPrepare
[2021-03-12 11:23:20,391] {logging_mixin.py:104} INFO - Running <TaskInstance: conversion_flow.taskPrepare 2021-03-12T11:23:18+00:00 [running]> on host 6299f34f884f
[2021-03-12 11:23:20,413] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=conversion_flow
AIRFLOW_CTX_TASK_ID=taskPrepare
AIRFLOW_CTX_EXECUTION_DATE=2021-03-12T11:23:18+00:00
AIRFLOW_CTX_DAG_RUN_ID=conversion_flow1615548198.567747
[2021-03-12 11:23:22,207] {python.py:118} INFO - Done. Returned value was: True
[2021-03-12 11:23:22,220] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=conversion_flow, task_id=taskPrepare, execution_date=20210312T112318, start_date=20210312T112320, end_date=20210312T112322
[2021-03-12 11:23:22,236] {taskinstance.py:1220} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2021-03-12 11:23:22,263] {local_task_job.py:146} INFO - Task exited with return code 0
