[2021-03-12 07:49:53,343] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: conversion_flow.taskSchemaConv 2021-03-12T07:49:49+00:00 [queued]>
[2021-03-12 07:49:53,352] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: conversion_flow.taskSchemaConv 2021-03-12T07:49:49+00:00 [queued]>
[2021-03-12 07:49:53,352] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2021-03-12 07:49:53,352] {taskinstance.py:1043} INFO - Starting attempt 1 of 1
[2021-03-12 07:49:53,352] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2021-03-12 07:49:53,357] {taskinstance.py:1063} INFO - Executing <Task(PythonOperator): taskSchemaConv> on 2021-03-12T07:49:49+00:00
[2021-03-12 07:49:53,359] {standard_task_runner.py:52} INFO - Started process 9193 to run task
[2021-03-12 07:49:53,361] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'conversion_flow', 'taskSchemaConv', '2021-03-12T07:49:49+00:00', '--job-id', '22', '--pool', 'default_pool', '--raw', '--subdir', '/srv/app/src/ckanext-mysql2mongodb/ckanext/mysql2mongodb/data_conv/dag/conversion_flow.py', '--cfg-path', '/tmp/tmp9jskctls', '--error-file', '/tmp/tmp1obmzwim']
[2021-03-12 07:49:53,362] {standard_task_runner.py:77} INFO - Job 22: Subtask taskSchemaConv
[2021-03-12 07:49:53,386] {logging_mixin.py:104} INFO - Running <TaskInstance: conversion_flow.taskSchemaConv 2021-03-12T07:49:49+00:00 [running]> on host 83c843b036e0
[2021-03-12 07:49:53,410] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=conversion_flow
AIRFLOW_CTX_TASK_ID=taskSchemaConv
AIRFLOW_CTX_EXECUTION_DATE=2021-03-12T07:49:49+00:00
AIRFLOW_CTX_DAG_RUN_ID=conversion_flow1615535388.994718
[2021-03-12 07:49:55,781] {logging_mixin.py:104} INFO - Generate MySQL database sakila successfully!
[2021-03-12 07:49:55,807] {logging_mixin.py:104} INFO - Save schema from sakila database to MongoDB successfully!
[2021-03-12 07:49:55,808] {conversion_flow.py:113} ERROR - Error Occure in taskDataConv Task!
[2021-03-12 07:49:55,808] {conversion_flow.py:114} ERROR - 'str' object has no attribute 'host'
[2021-03-12 07:49:55,808] {taskinstance.py:1455} ERROR - 'str' object has no attribute 'host'
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/airflow/models/taskinstance.py", line 1112, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/usr/local/lib/python3.6/dist-packages/airflow/models/taskinstance.py", line 1285, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/usr/local/lib/python3.6/dist-packages/airflow/models/taskinstance.py", line 1315, in _execute_task
    result = task_copy.execute(context=context)
  File "/usr/local/lib/python3.6/dist-packages/airflow/operators/python.py", line 117, in execute
    return_value = self.execute_callable()
  File "/usr/local/lib/python3.6/dist-packages/airflow/operators/python.py", line 128, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/srv/app/src/ckanext-mysql2mongodb/ckanext/mysql2mongodb/data_conv/dag/conversion_flow.py", line 115, in taskSchemaConv
    raise exception
  File "/srv/app/src/ckanext-mysql2mongodb/ckanext/mysql2mongodb/data_conv/dag/conversion_flow.py", line 103, in taskSchemaConv
    schema_conversion.run()
  File "/srv/app/src/ckanext-mysql2mongodb/ckanext/mysql2mongodb/data_conv/schema_conversion.py", line 38, in run
    self.save_schema_view()
  File "/srv/app/src/ckanext-mysql2mongodb/ckanext/mysql2mongodb/data_conv/schema_conversion.py", line 432, in save_schema_view
    self.load_schema()
  File "/srv/app/src/ckanext-mysql2mongodb/ckanext/mysql2mongodb/data_conv/schema_conversion.py", line 66, in load_schema
    db_schema = load_mongodb_collection(self.schema_conv_output_option.host, "schema")
  File "/srv/app/src/ckanext-mysql2mongodb/ckanext/mysql2mongodb/data_conv/utilities.py", line 113, in load_mongodb_collection
    mongodb_connection = open_connection_mongodb(schema_conv_output_option)
  File "/srv/app/src/ckanext-mysql2mongodb/ckanext/mysql2mongodb/data_conv/utilities.py", line 97, in open_connection_mongodb
    connection_string = f"mongodb://{schema_conv_output_option.host}:{schema_conv_output_option.port}/"
AttributeError: 'str' object has no attribute 'host'
[2021-03-12 07:49:55,809] {taskinstance.py:1503} INFO - Marking task as FAILED. dag_id=conversion_flow, task_id=taskSchemaConv, execution_date=20210312T074949, start_date=20210312T074953, end_date=20210312T074955
[2021-03-12 07:49:55,821] {local_task_job.py:146} INFO - Task exited with return code 1
